name: ci
on:
  push:
    branches:
      - main
      - release/*
      - feat/*
      - fix/*
      - perf/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install Dependencies
        run: npm ci

  build:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install Dependencies
        run: npm ci
      - name: Test Build
        run: npm run build

  test:
    needs: [install, build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit & Component Tests
        run: npm run test-ci --if-present

  # frontend_lint:
  #   needs: [changes, install]
  #   if: ${{ needs.changes.outputs.frontend == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #         cache: "npm"
  #         cache-dependency-path: "**/package-lock.json"
  #     - run: npm ci
  #     - run: npm run lint:frontend

  # backend_test:
  #   needs: [changes, install]
  #   if: ${{ needs.changes.outputs.backend == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #         cache: "npm"
  #         cache-dependency-path: "**/package-lock.json"
  #     - run: npm ci
  #     - run: npm run test:backend
  #     - name: Coveralls
  #       uses: coverallsapp/github-action@master
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}

  # angularjs_test:
  #   needs: [changes, install]
  #   if: ${{ needs.changes.outputs.angularjs == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #         cache: "npm"
  #         cache-dependency-path: "**/package-lock.json"
  #     - run: npm ci
  #     - run: npm run test:angularjs

  # src_lint:
  #   needs: [changes, install]
  #   if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.angularjs == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #         cache: "npm"
  #         cache-dependency-path: "**/package-lock.json"
  #     - run: npm ci
  #     - run: npm run lint-ci

  # src_e2e:
  #   needs: [changes, build]
  #   if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.angularjs == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #         cache: "npm"
  #         cache-dependency-path: "**/package-lock.json"
  #     - run: npm ci
  #     - run: npm run test-e2e
